### ISSUE TITLE
Attempting to share via facebook leads to yourdomain.com

### ISSUE THREAD

**Issue by liamdawson** [eliasbagley/eliasbagley.github.io#1]
I just saw [your post about Android plugins](http://eliasbagley.github.io/android/2015/10/04/essential-android-studio-plugins.html), and shared it with a friend via Facebook Messenger on Android. Following that link lead my friend to http://yourdomain.com/android/2015/10/04/essential-android-studio-plugins.html.

I think I've identified the cause in the attached picture, I'm guessing it's a bit of config you've missed somewhere?

![Aforementioned attached picture](https://cloud.githubusercontent.com/assets/760143/10272461/1b3dd65c-6b63-11e5-892d-e4376954b37a.png)

**Comment by eliasbagley** [comment]
Fix merged
